apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-ingress
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: sp-svc
            servicePort: 8080
        - path: /customer
          backend:
            serviceName: ct-svc
            servicePort: 8080
        - path: /order
          backend:
            serviceName: od-svc
            servicePort: 8080
