apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: www.app.com
    http:
      paths:
      pathType: Prefix
      - backend:
          service:
            name: v1-svc
            port: 
              number: 8080
