apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: container
    image: redis
    volumeMounts:
    - name: pod2
      mountPath: /mount1
  volumes:
  - name : pod2
    persistentVolumeClaim:
      claimName: pvc
